---
title: "p8105_hw2_cn2604"
output: github_document
date: "2022-09-27"
---

```{r load_library,echo = FALSE, message=FALSE}
library(tidyverse)
```
# Problem 1
```{r read_file}
transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    entry = recode(entry, 'YES' = 'TRUE', 'NO' = 'FLASE'),
    entry = as.logical(entry),
    corner = as.factor(corner),
    staffing = as.factor(staffing),
    entrance_type = as.factor(entrance_type),
    division = as.factor(division),
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
  ) %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) %>% 
  unite(col = 'unique_station_name', c('station_name', 'line'), sep = ' ')
  
  
```
The primary variables of this dataset are the name and location of the stations, their divisions and lines with different routes, the types of entrance and their locations. Other additional information such as presence of staffs, vending, ADA, and crossing over are also provided.



